apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules: 
  - host: {{.Values.Domain}}
    http:
      paths:
      - path: /foo
        backend:
          serviceName: nodeport
          servicePort: 80
